on: 
  push:
    branches:
      - master
      - v1.11_RC

jobs:
  doc_build_job:
    runs-on: ubuntu-latest
    # This project MUST be given permission to use the image blow. at
    # Package settings-> Manage action access of the project hosting the
    # package
    # Your project MUST contain empty .nojekyll file. Github Pages will
    # discard everything starting with '_' i.e. the stylefiles.
    container: 'ghcr.io/thesystemdevelopmentkit/thesdktestimage:latest'
    name: Build documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Documentation builder action
        run:  cd doc && make html && cd .. && mv ./doc/build/html/* ./docs/
      - name: GIT commit and push documentation
        env:
              CI_COMMIT_MESSAGE: Continuous Integration documentation update
              CI_COMMIT_AUTHOR: Continuous Integration
        run: git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}" && git config --global user.email "${GITHUB_ACTOR}@noreply.github.com" && git add docs && git commit -m "${{ env.CI_COMMIT_MESSAGE }}" && git push

